title: MovtiGroup
email: info@movtigroup.me
description: >-
  Landing page رسمی MovtiGroup روی GitHub Pages.
baseurl: ""
url: "https://movtigroup.me"
twitter_username: movtigroup
github_username:  movtigroup

# Permalinks configuration
permalink: /blog/:title/

# Build settings
# theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      lang: "fa"
      dir: "rtl"
paginate: 6
paginate_path: "/blog/page:num/"
