title: MovtiGroup
email: info@movtigroup.me
description: >-
  Landing page رسمی MovtiGroup روی GitHub Pages.
baseurl: ""
url: "https://movtigroup.me"
twitter_username: movtigroup
github_username:  movtigroup

# Build settings
# theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2

# Multilingual defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"
      lang: "fa"
      dir: "rtl"

# Collections configuration
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Pagination
pagination:
  enabled: true
  per_page: 12
  permalink: '/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true
