title: MovtiGroup
email: info@movtigroup.me
description: >-
  Landing page رسمی MovtiGroup روی GitHub Pages.
baseurl: ""
url: "https://movtigroup.me"
twitter_username: movtigroup
github_username:  movtigroup

# Permalinks configuration
permalink: /blog/:title/

# Build settings
# theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      lang: "fa"
      dir: "rtl"


pagination:
  enabled: true
  debug: false
  per_page: 6
  permalink: '/page:num/'
  title_suffix: ' - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  indexpage: 'index'
